1 EM QUAL PROGRAMA O CALCULO FOI EXECUTADO?
R: def calcular_pontos(valor_compra, pontos_por_real):
    return valor_compra * pontos_por_real

2 QAUL O PROGRAMA INICIOU A SOLICITAÇÃO?
R:resultado = servidor.calcular_pontos(120, 2)

O QUE ACONTECERIA COM O CLIENTE SER O SERVIDOR ESTIVESSSE DESLIGADO?
R:Se você executar o cliente.py sem o Servidor.py estar funcionando, o cliente tentará se conectar à porta 8004, mas não encontrará o servidor.

